# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/models/messages.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'src/models/messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19src/models/messages.proto\">\n\nMsgPayload\x12\n\n\x02sn\x18\x01 \x01(\r\x12\n\n\x02\x65t\x18\x02 \x01(\r\x12\n\n\x02ts\x18\x03 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\">\n\x10MsgTriaxialValue\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\t\n\x01m\x18\x04 \x01(\x02\"\xb7\x01\n\x0cMsgRmsReport\x12\x1e\n\x03rms\x18\x01 \x01(\x0b\x32\x11.MsgTriaxialValue\x12\x1f\n\x04peak\x18\x02 \x01(\x0b\x32\x11.MsgTriaxialValue\x12 \n\x05\x63rest\x18\x03 \x01(\x0b\x32\x11.MsgTriaxialValue\x12\"\n\x07impulse\x18\x04 \x01(\x0b\x32\x11.MsgTriaxialValue\x12\x13\n\x0btemperature\x18\x05 \x01(\x02\x12\x0b\n\x03iso\x18\x06 \x01(\r\">\n\x10MsgMachineStatus\x12\x1e\n\x03rms\x18\x01 \x01(\x0b\x32\x11.MsgTriaxialValue\x12\n\n\x02st\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.models.messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MSGPAYLOAD']._serialized_start=29
  _globals['_MSGPAYLOAD']._serialized_end=91
  _globals['_MSGTRIAXIALVALUE']._serialized_start=93
  _globals['_MSGTRIAXIALVALUE']._serialized_end=155
  _globals['_MSGRMSREPORT']._serialized_start=158
  _globals['_MSGRMSREPORT']._serialized_end=341
  _globals['_MSGMACHINESTATUS']._serialized_start=343
  _globals['_MSGMACHINESTATUS']._serialized_end=405
# @@protoc_insertion_point(module_scope)
